### PR TITLE
Fetch missions api

### PR DESCRIPTION
**Pull request by ReemMohamedAbdelfatah**
In this pull request, the followings are done:

- Fetch data from the Missions endpoint.
- dispatch an action to store the selected data in the Redux store
- Use useSelector () Redux Hook to select the state slices and render lists of missions in corresponding routes.

### CODE REVIEW

**Review by Fahim-Khan-P — CHANGES_REQUESTED** [review]
# 🟢 Review changes! 🏆

## Hi @ReemMohamedAbdelfatah   👋

Your project is near to complete! ✔️ 🏁

**but you have two conflicts in your src/index.js file, as you can see the conflict in your pull request link after linters check try to resolve it!.**
click on the link to see the conflict: https://github.com/ReemMohamedAbdelfatah/Space-Travelers-Hub/pull/50
 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

**Comment by ReemMohamedAbdelfatah** [comment]
Hello, @Fahim-Khan-P Conflicts resolved. thank you!

**Review by Fahim-Khan-P — APPROVED** [review]
Hi @ReemMohamedAbdelfatah,
This is @Fahim-Khan-P your code reviewer  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

chelsea-mason-approve


## Highlights
Project working as expected :+1: 
No linter errors :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you! @Fahim-Khan-P

**Pull request merged**
